### PR TITLE
merging changes and bug fixes from Harrison

### PR DESCRIPTION
**Pull request by mreinstein**
as per #1 I reached out to @hxa7241 and he was kind enough to send me the updated working code. :) Seems to work! I've also added his TODO notes to the README. I can submit another PR with background worker stuff if that'd be helpful.

### CODE REVIEW

**Comment by hxa7241** [comment]
This pull-request ought to be declined.

It is, it seems, merely a chunk of stuff done by hxa7241 and/or darius, therefore ought not to be simply submitted by someone else.

An archive of the files (as last worked on by hxa7241) is available at:
   http://www.hxa.name/minilight/minilight153js-unfinished.tar.gz

**Comment by mreinstein** [comment]
> merely a chunk of stuff done by hxa7241 and/or darius, therefore ought not to be simply submitted by someone else.

why? I guess I don't understand why this is a problem. The project has been sitting untouched for 3 years. Surely an incomplete port helps no one.

**Comment by darius** [comment]
Hi again! Sorry I've been so scarce. (Moving over the weekend, and more has come up than planned.) @mreinstein, I'll bet I'd be happy to merge your work once I've had a chance to look, but I don't plan on maintaining this repo -- it'd be best to update the README here to point to fresher sources, like a fork by you? And Harrison's now that there's a URL. That I can do without reviewing anything first.

**Comment by mreinstein** [comment]
@hxa7241 maybe this gets moved to https://github.com/hxa7241/minilight-js ? I noticed you're maintaining ports for other languages there and they seem up to date.

I didn't meant to step on anyone's toes by pushing these changes. I figured this would be helpful for other people investigating minilight. I'd rather roll up my sleeves and send a PR than complain and expect someone else to do the work. :)

**Comment by hxa7241** [comment]
OK: the 'latest' stuff has been added to https://github.com/hxa7241/minilight.js and anyone else may now have at it as they please !

**Comment by mreinstein** [comment]
@hxa7241 I think @darius could actually transfer ownership of this repo to you. If Darius isn't planning to maintain this it's preferable to having a leftover copy lying around and pointing to your repo. Anyone visiting the old url (https://github.com/darius/minilight.js) would automatically get redirected to you (https://github.com/hxa7241/minilight.js)

anyway, this isn't a big deal but it would be nice to have one less old copy lying around. :)

**Comment by darius** [comment]
I didn't know you could do that. I'd be willing.

**Comment by mreinstein** [comment]
if you click the settings button, it's at the bottom of the settings page in the danger zone "Transfer ownership"

**Pull request closed without merging**
